

name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: 'true'
    - uses: lysts/pelican-to-github-pages@v1.0.3
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: ${{secrets.CNAME}}

PELICAN_CONFIG_FILE: pelicanconf.py
PELICAN_CONTENT_FOLDER: content
PYTHON_VERSION: 3.11.1

