name: build

on: [push, pull_request]

env:
  # color output for pytest and tox
  PYTEST_ADDOPTS: "--color=yes"
  PY_COLORS: 1

jobs:
  test:
    name: Test - ${{ matrix.config.python }} - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}-latest

    strategy:
      matrix:
        config:
          - os: ubuntu
            python: "3.7"
          - os: ubuntu
            python: "3.8"
          - os: ubuntu
            python: "3.9"
          - os: ubuntu
            python: "3.10"
          - os: ubuntu
            python: "3.11"
          - os: macos
            python: "3.7"
          - os: windows
            python: "3.7"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.config.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config.python }}
          cache: 'pip'
          cache-dependency-path: '**/requirements/*'
      - name: Install locale (Linux)
        if: startsWith(runner.os, 'Linux')
        run: sudo locale-gen fr_FR.UTF-8 tr_TR.UTF-8
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.9.2"
      - name: Install tox
        run: python -m pip install -U pip tox
      - name: Info
        run: |
          echo "=====  PYTHON  ====="
          python --version
          echo "=====  PANDOC  ====="
          pandoc --version | head -2
      - name: Run tests
        run: tox -e py${{ matrix.config.python }}


  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
          cache-dependency-path: '**/requirements/*'
      - name: Install tox
        run: python -m pip install -U pip tox
      - name: Check
        run: tox -e flake8


  docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
          cache-dependency-path: '**/requirements/*'
      - name: Install tox
        run: python -m pip install -U pip tox
      - name: Check
        run: tox -e docs


  deploy:
    name: Deploy
    environment: Deployment
    needs: [test, lint, docs]
    runs-on: ubuntu-latest
    if: github.ref=='refs/heads/master' && github.event_name!='pull_request'

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check release
        id: check_release
        run: |
          python -m pip install --upgrade pip
          python -m pip install autopub[github]
          autopub check

      - name: Publish
        if: ${{ steps.check_release.outputs.autopub_release=='true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          autopub prepare
          autopub commit
          autopub build
          autopub githubrelease

      - name: Upload package to PyPI
        if: ${{ steps.check_release.outputs.autopub_release=='true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
